### ISSUE TITLE
Audio very poppy / droputs on firefox

### ISSUE THREAD

**Issue by wrightwriter** [FMS-Cat/wavenerd#8]
A couple of people who tested this are getting it on firefox, with different GPUs.
Might be related to the error below.
![image](https://user-images.githubusercontent.com/8731857/110205257-b48cba00-7e7f-11eb-8d80-938b141c0306.png)

**Comment by wrightwriter** [comment]
Chrome also has popping, but around every second. No matter if OpenGL/Angle.

btw, I am Windows gtx 2080m

**Comment by 0b5vr** [comment]
fixed???? replaced with audioworklet with somewhat better algorithm
